### PR TITLE
Csas

### PR DESCRIPTION
**Pull request by yc-hu**
Hi David, Could you please deploy it to the production site? Thanks!

### CODE REVIEW

**Comment by yc-hu** [comment]
Hi David, Could you please deploy it to the production site? Thanks!

**Review by davjfish — CHANGES_REQUESTED** [review]
Sorry guys, I'm sending this one back. We will have to have some more discussion around this.

**Comment by upsonp** [comment]
Ouch. That's a lot of json files 😄

**Comment by yc-hu** [comment]
Hi David, I removed all the fixtures for publication, also updated create meeting and go to meeting parts, pushed to github minutes ago, could you please deploy it to the production site? Thanks!
I will send the json file to Patrick by email, the json file contains 500 publications, let's see how it goes, I don't want to load 8700 records, then find some problems :-)

**Pull request closed without merging**
